name: Build And Test Docker Image
run-name: ${{ github.actor }} is Building Docker Image 🚀
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build . --tag ghcr.io/barnes2197/flexport-take-home:latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker Image
        run: |
          docker push ghcr.io/maubarnes/flexport-take-home:latest
      